on:
  workflow_dispatch:
jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "The job is running"
        if: ${{ !contains(github.event.head_commit.message, 'WIP') }}
